# Generated by Django 3.2.25 on 2025-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_image', models.ImageField(upload_to='images/id/')),
                ('id_image', models.ImageField(upload_to='images/camera/')),
            ],
        ),
    ]
